### PR TITLE
Make registration of BearerTokenRequestInterceptor optional

### PR DESCRIPTION
**Pull request by jan-olaveide**
As pr https://github.com/navikt/token-support/issues/423

### CODE REVIEW

**Review by tommytroen — COMMENTED** [review]
Can we use `@ConditionalOnProperty`? And find some way to set the default to true?
E.g. 
```kotlin
@Bean
@ConditionalOnProperty("no.nav.security.jwt.propagate-bearertoken")
fun bearerTokenClientHttpRequestInterceptor(): BearerTokenClientHttpRequestInterceptor {}
```

**Comment by jan-olaveide** [comment]
Det burde også være mulig, kanskje bedre

**Comment by tommytroen** [comment]
> Can we use `@ConditionalOnProperty`? And find some way to set the default to true? E.g.
> 
> ```kotlin
> @Bean
> @ConditionalOnProperty("no.nav.security.jwt.propagate-bearertoken")
> fun bearerTokenClientHttpRequestInterceptor(): BearerTokenClientHttpRequestInterceptor {}
> ```

Or we could maybe do:

```kotlin
@Bean
@ConditionalOnProperty("no.nav.security.jwt.dont-propagate-bearertoken", matchIfMissing="true")
fun bearerTokenClientHttpRequestInterceptor(): BearerTokenClientHttpRequestInterceptor {}
```

**Comment by jan-olaveide** [comment]
PR updated, @tommytroen

**Pull request merged**
